### ISSUE TITLE
mt7620 ap and adhoc could not working at same time.

### ISSUE THREAD

**Issue by chaokw** [widora/openwrt_widora#1]
modify /etc/config/wireless to enable two interface  ap0 and adhoc0, but could not working at same time.
only using ap0 or adhoc0 is ok.

config wifi-device  radio0
        option type     mac80211
        option channel  10
        option hwmode   11n
        option path     '10180000.wmac'
        option htmode HT40
        option txpower 20
        option country 00
        option beacon_int 3000

config wifi-iface
        option device   radio0
        option ifname   ap0
        option network  lan
        option mode     ap
        option ssid     openwrt_test
        option encryption none
        option wmm 0

config wifi-iface
        option device   radio0
        option ifname   adhoc0
        option encryption none
        option network  mesh
        option mode     adhoc
        option ssid 'mesh'

**Comment by YuanChenmang** [comment]
widora don't support MT7620 platform.
