### ISSUE TITLE
shairport has noise since 0.0.17 RC1

### ISSUE THREAD

**Issue by yonhdee** [widora/openwrt_widora#9]
shairport has noise, sounds like little pops, once every second, installed upmpdcli and tested with the same result

**Comment by YuanChenmang** [comment]
You test it on which board?

**Comment by yonhdee** [comment]
Widora NEO

**Comment by YuanChenmang** [comment]
make a test :  aplay xxxx.wav
if you found noise also,maybe the hardware problem. 
in NEO board, wm8960 and ddr2 too close, may not be very good deal

**Comment by yonhdee** [comment]
in firmware 0.0.16, sound outputs(shairport, upmpdcli, gmediarender) are ok, maybe its not about hardware
